<?php $this->partial('shared/header'); ?>

<form method="post" class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <div class="pull-right">
                    <a class="btn btn-default" href="<?= $next ?>">Cancel</a>
                    <button class="btn btn-primary">Save</button>
                </div>
                <h3><?= $title ?></h3>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-4">
            <?= $this->form->field('title') ?>
            <?= $this->form->field('group', $groups) ?>
            <?= $this->form->field('text') ?>
        </div>
        <div class="col-md-4">
            <?= $this->form->field('image') ?>
            <?= $this->form->field('sources') ?>
        </div>
    </div>
</form>

<?php $this->partial('shared/footer'); ?>